routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\HomeConrtoller;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterConrtoller;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route("blog.index");
});
Route::get("login", [LoginController::class, "showLoginForm"])->name('login-form');
Route::post("login", [LoginController::class, "login"])->name('login');
Route::get("register", [RegisterConrtoller::class, "showRegisterForm"])->name('register-form');
Route::post("register", [RegisterConrtoller::class, "register"])->name('register');
Route::post('logout', [HomeConrtoller::class, 'logout'])->name("logout");
Route::get("home", function() {
    return redirect()->route("blog.index");
})->name("home");
Route::resource("blog", BlogController::class);

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Blog extends Model
{
    use HasFactory;

    protected $fillable = [
        "title", "description", "start_date", "end_date", "is_active", "image", "user_id"
    ];

    public function scopeRole(Builder $query)
    {
        if(auth()->user()->role != "admin"){
            $query->where("user_id", auth()->id());
        }
    }

    public function scopeActive(Builder $query)
    {
        $query->where("is_active", 1);
    }

    public function scopeNotExpired(Builder $query)
    {
        $query->whereDate("end_date", ">=", date("Y-m-d"));
    }
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::latest()->active()->notExpired();

        if(auth()->user()){
            $blogs->role();
        }

        $blogs = $blogs->paginate(10);

        return view("blog.index", compact('blogs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(!auth()->check()){
            return redirect()->route("login-form", ["redirect" => route("blog.create")]);
        }
        return view("blog.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if(!auth()->check()){
            return redirect()->route("login-form", ["redirect" => route("blog.create")]);
        }

        $this->validate($request, [
            "title" => "required|max:255",
            "description" => "required",
            "start_date" => "required|date",
            "end_date" => "required|date|after_or_equal:start_date",
            "image" => "required|image|max:2048",
            "is_active" => "required|in:0,1"
        ]);

        Blog::create([
            "title" => $request->title,
            "description" => $request->description,
            "start_date" => date('Y-m-d', strtotime($request->start_date)),
            "end_date" => date('Y-m-d', strtotime($request->end_date)),
            "image" => "/storage/".$request->file('image')->store("blogs"),
            "user_id" => auth()->id(),
            "is_active" => $request->is_active,
        ]);

        return redirect()->route("blog.index")->with('message', "Blog created successfully.");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $blog = Blog::where("id", $id);

        if(auth()->check()){
            $blog->role();
        }

        $blog = $blog->firstOrFail();

        return view("blog.show", compact("blog"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!auth()->check()){
            return redirect()->route("login-form", ["redirect" => route("blog.edit")]);
        }

        $blog = Blog::role()->where(["id" => $id])->firstOrFail();
        return view("blog.edit",  compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(!auth()->check()){
            return redirect()->route("login-form", ["redirect" => route("blog.edit")]);
        }

        $blog = Blog::role()->where(["id" => $id])->firstOrFail();

        $this->validate($request, [
            "title" => "required|max:255",
            "description" => "required",
            "start_date" => "required|date",
            "end_date" => "required|date|after_or_equal:start_date",
            "image" => "nullable|image|max:2048",
            "is_active" => "required|in:0,1"
        ]);

        $data = [
            "title" => $request->title,
            "description" => $request->description,
            "start_date" => date('Y-m-d', strtotime($request->start_date)),
            "end_date" => date('Y-m-d', strtotime($request->end_date)),
            "is_active" => $request->is_active
        ];

        if($request->hasFile('image')){
            $data["image"] = "/storage/".$request->file('image')->store("blogs");
        }

        $blog->update($data);

        return redirect()->route("blog.index")->with('message', "Blog updated successfully.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $blog = Blog::role()->where(["id" => $id])->firstOrFail();
        $blog->delete();

        return redirect()->route("blog.index")->with('message', "Blog deleted successfully.");
    }
}

resources/views/blog/create.blade.php
@extends('layout')

@section('content')
<h2 class="text-center">Add New Blog</h2>
<div class="card mt-4">
    <div class="card-body">
        <form action="{{route('blog.store')}}" id="blog-form" enctype="multipart/form-data" method="POST">
            @csrf
            <div class="form-group">
                <label for="">Title</label>
                <input type="text" class="form-control" name="title" placeholder="Enter title" value="{{old('title')}}">
                @error('title')
                <span class="text-danger">{{$message}}</span>
                @enderror
            </div>

            <div class="form-group mt-3">
                <label for="">Description</label>
                <textarea name="description" class="form-control" id="" placeholder="Enter Description">{{old('description')}}</textarea>
                @error('description')
                <span class="text-danger">{{$message}}</span>
                @enderror
            </div>

            <div class="form-group  mt-3">
                <div class="row">
                    <div class="col-md-6">
                        <label for="">Start Date</label>
                        <input type="date" class="form-control" name="start_date" value="{{old('start_date')}}">
                        @error('start_date')
                        <span class="text-danger">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="col-md-6">
                        <label for="">End Date</label>
                        <input type="date" class="form-control" name="end_date" value="{{old('end_date')}}">
                        @error('end_date')
                        <span class="text-danger">{{$message}}</span>
                        @enderror
                    </div>
                </div>
            </div>

            <div class="form-group mt-3">
                <label for="">Image</label>
                <input type="file" name="image" class="form-control">
                @error('image')
                <span class="text-danger">{{$message}}</span>
                @enderror
            </div>

            <div class="form-group mt-3">
                <label for="">Status</label>
                <select name="is_active" id="" class="form-control">
                    <option value="1">Active</option>
                    <option value="0">Inactive</option>
                </select>
                @error('is_active')
                <span class="text-danger">{{$message}}</span>
                @enderror
            </div>

            <div class="form-group mt-3">
                <button type="button" id="btn-save-blog" class="btn btn-primary">Save Blog</button>
            </div>
        </form>
    </div>
</div>
@endsection

@section('js')
<script>
    $(document).ready(function(){
        $("#btn-save-blog").click(function(){
            if($("input[name='title']").val() == ""){
                alert("Title field is required");
            }else if($("textarea[name='description']").val() == ""){
                alert("Description field is required");
            }else if($("input[name='start_date']").val() == ""){
                alert("Start date field is required");
            }else if($("input[name='end_date']").val() == ""){
                alert("End date field is required");
            }else if($('input[name="image"]').get(0).files.length === 0){
                alert("Image field is required");
            }else if($("select[name='is_active']").val() == ""){
                alert("Status field is required");
            }else{
                $("#blog-form").submit();
            }
        })
    })
</script>
@endsection

resources/views/blog/edit.blade.php
@extends('layout')

@section('content')
<h2 class="text-center">Add New Blog</h2>
<div class="card mt-4">
    <div class="card-body">
        <form action="{{route('blog.update', $blog->id)}}" id="blog-form" enctype="multipart/form-data" method="POST">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="">Title</label>
                <input type="text" class="form-control" name="title" placeholder="Enter title" value="{{old('title', $blog->title)}}">
                @error('title')
                <span class="text-danger">{{$message}}</span>
                @enderror
            </div>

            <div class="form-group mt-3">
                <label for="">Description</label>
                <textarea name="description" class="form-control" id="" placeholder="Enter Description">{{old('description', $blog->description)}}</textarea>
                @error('description')
                <span class="text-danger">{{$message}}</span>
                @enderror
            </div>

            <div class="form-group  mt-3">
                <div class="row">
                    <div class="col-md-6">
                        <label for="">Start Date</label>
                        <input type="date" class="form-control" name="start_date" value="{{old('start_date', date('Y-m-d', strtotime($blog->start_date)))}}">
                        @error('start_date')
                        <span class="text-danger">{{$message}}</span>
                        @enderror
                    </div>
                    <div class="col-md-6">
                        <label for="">End Date</label>
                        <input type="date" class="form-control" name="end_date" value="{{old('end_date', date('Y-m-d', strtotime($blog->end_date)))}}">
                        @error('end_date')
                        <span class="text-danger">{{$message}}</span>
                        @enderror
                    </div>
                </div>
            </div>

            <div class="form-group mt-3">
                <label for="">Image (Optional)</label>
                <input type="file" name="image" class="form-control">
                @error('image')
                <span class="text-danger">{{$message}}</span>
                @enderror
            </div>

            <div class="form-group mt-3">
                <label for="">Status</label>
                <select name="is_active" id="" class="form-control">
                    <option value="1" {{$blog->is_active == 1 ? "selected" : ""}}>Active</option>
                    <option value="0" {{$blog->is_active != 1 ? "selected" : ""}}>Inactive</option>
                </select>
                @error('is_active')
                <span class="text-danger">{{$message}}</span>
                @enderror
            </div>

            <div class="form-group mt-3">
                <button type="button" class="btn btn-primary" id="btn-save-blog">Save Blog</button>
            </div>
        </form>
    </div>
</div>
@endsection

@section('js')
<script>
    $(document).ready(function(){
        $("#btn-save-blog").click(function(){
            if($("input[name='title']").val() == ""){
                alert("Title field is required");
            }else if($("textarea[name='description']").val() == ""){
                alert("Description field is required");
            }else if($("input[name='start_date']").val() == ""){
                alert("Start date field is required");
            }else if($("input[name='end_date']").val() == ""){
                alert("End date field is required");
            }else if($("select[name='is_active']").val() == ""){
                alert("Status field is required");
            }else{
                $("#blog-form").submit();
            }
        })
    })
</script>
@endsection

resources/views/blog/index.blade.php
@extends('layout')

@section('content')
@if(count($blogs) == 0)
<div class="card mt-4">
    <div class="card-body">
    No blogs found.
    </div>
</div>
@else 
<div class="card mt-4">
    <div class="card-body">
        @if(Session::has('message'))
        <div class="alert alert-success">
            {{Session::get('message')}}
        </div>
        @endif
        @foreach($blogs as $blog)
        <div class="row mt-3">
            <div class="col-md-4">
                <img src="{{asset($blog->image)}}" class="image-responsive" style="width:300px;height:200px" alt="">
            </div>
            <div class="col-md-8">
                <div class="title">
                    <h2>{{$blog->title}}</h2>
                </div>
                <div class="description">
                    {{ strlen($blog->description) > 200 ? substr($blog->description, 0 , 200)."..." : $blog->description }}
                    <a href="{{route('blog.show', $blog->id)}}">Read Full article</a>
                </div>
                <br>
                <div class="option" style="display: flex;">
                    @auth
                    <a href="{{route('blog.edit', $blog->id)}}" class="btn btn-success">Edit</a>&nbsp;
                    <form action="{{route('blog.destroy', $blog->id)}}" method="POST">
                        @csrf
                        @method("DELETE")
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure want to delete?')">DELETE</button>
                    </form>
                    @endauth
                </div>
            </div>
        </div>
        @endforeach
        <br><br>
        {{$blogs->links()}}
    </div>
</div>
@endif
@endsection

resources/views/blog/show.blade.php
@extends('layout')

@section('content')
<div class="card mt-4">
    <div class="card-body">
        @if(Session::has('message'))
        <div class="alert alert-success">
            {{Session::get('message')}}
        </div>
        @endif
        <div class="row mt-3">
            <div class="col-md-4">
                <img src="{{asset($blog->image)}}" class="image-responsive" style="width:300px;height:200px" alt="">
            </div>
            <div class="col-md-8">
                <div class="title">
                    <h2>{{$blog->title}}</h2>
                </div>
                <div class="description">
                    {{ $blog->description }}
                </div>
                <br>
                <div class="option" style="display: flex;">
                    @auth
                    <a href="{{route('blog.edit', $blog->id)}}" class="btn btn-success">Edit</a>&nbsp;
                    <form action="{{route('blog.destroy', $blog->id)}}" method="POST">
                        @csrf
                        @method("DELETE")
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure want to delete?')">DELETE</button>
                    </form>
                    @endauth
                </div>
            </div>
        </div>
    </div>
</div>
@endsection